version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "master"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl

- package-ecosystem: npm
  target-branch: stable25
  versioning-strategy: lockfile-only
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  open-pull-requests-limit: 30
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: npm
  target-branch: stable24
  versioning-strategy: lockfile-only
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  open-pull-requests-limit: 30
  labels:
  - 3. to review
  - dependencies

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
- package-ecosystem: composer
  directory: "/tests/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - juliushaertl
